apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 082683139344.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 082683139344.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: a4322e2e
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
